server:
  port: 10001

system: prod

spring:
  datasource:
    url: jdbc:mysql://172.18.1.1:3306/user_center
    hikari:
      username: root
      password: meisql
      driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include:
      - dubbo
      - dversion
      - swagger
      - job
  main:
    web-application-type: reactive
