server:
  port: 10001

spring:
  application:
    name: rical-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.2.1:8848
  datasource:
    url: jdbc:mysql://172.18.1.1:3306/user_center
    hikari:
      username: root
      password: meisql
      driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include:
      - dubbo
      - dversion
      - swagger
      - job
  main:
    web-application-type: reactive
