server:
  port: 10001

system: dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: meisql
      driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include:
      - dubbo
      - dversion
      - swagger
      - job